# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name=b'post_data',
            new_name='post_date',
        ),
    ]
