# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_auto_20180214_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('like_post', 'like_author')]),
        ),
    ]
