# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-06 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20180706_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
