# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20180214_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'loginsys/static/profile_image'),
        ),
    ]
