# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20180214_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='photo',
        ),
    ]
