# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0005_auto_20180214_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
