# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0007_auto_20180215_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default=b"post_image/default/default.jpg')", upload_to=b'profile_image'),
        ),
    ]
